### ISSUE TITLE
As a voter I need to view candidate information so I can decide who to vote for.

### ISSUE THREAD

**Issue by MikeJDev** [hratx39-blue-ocean/deep-dive#11]
Why: The voter needs a way to see information about potential candidates when they access the candidates selection page such as their: name, party, state, recent tweets, voting record, platform, campaign page link, approval rating, etc. 

How: When the user navigates to the candidates page it will display then with a list of clickable candidates which will then navigate to a specific candidates page with all the relevant info from above. 

Criteria: Need an api(s) that provide with all this information, set up routes from client to server to database with the relevant queries to the DB in order to retrieve the information.

**Comment by Kyruski** [comment]
Grabbing static information is done.
