### ISSUE TITLE
Change route path to candidate last names

### ISSUE THREAD

**Issue by remingtonjdavis** [hratx39-blue-ocean/deep-dive#156]
Candidate Cards is currently passing a candidates name as a prop to Candidate Details. The prop is also the file path with Reach Router making the url case sensitive to display accurate information. 
Typing in a candidates last name at /candidates/candidatedetails/lastname or /candidates/candidatedetails/Lastname should render the proper candidate detail page.
The page should default at the very top of the candidate information page when clicked.

**Comment by Kyruski** [comment]
Completed in #168
