### ISSUE TITLE
Implement Istanbul to measure test coverage

### ISSUE THREAD

**Issue by tdsmith27** [hratx39-blue-ocean/deep-dive#16]

**Comment by tdsmith27** [comment]
Why: So we can have a sense of how much of our code is being covered by our tests

How: add --coverage to the test script

ACCEPTANCE CRITERIA: 

- Once --coverage has been added to the test script, you are done

If Jest, done, if not, reassess

**Comment by scottkelder** [comment]
As above: If testing in Jest, add --coverage.

If testing in mocha/chai: 
1. npm install --save-dev nyc
2. add 'nyc' in front of any package.json script to run mocha tests

Backend testing: 
Coverage isn't relevant. If we're getting excellent coverage on the front end, we'll be covering the only backend pieces users can touch at the same time. The only other kind of backend testing we should do is stress testing to see how it holds up under load.
