### ISSUE TITLE
As a user, I want to understand what the candidate believes in so I know whether or not I will support them.

### ISSUE THREAD

**Issue by noahspann** [hratx39-blue-ocean/deep-dive#24]

**Comment by ant811** [comment]
Acceptance Criteria:
 - Falls under "Candidate Details card"
 - Includes Bio, Photo, Tweets, Link to Campaign page, voting history, donors, approval rating, platform, affiliation 
 - Overlay is Facebook style page
 - Has top navigation bar

**Comment by Kyruski** [comment]
Grabbing static information is done
