### ISSUE TITLE
As a user, I want to be able to click on a Candidate card to see the in-depth details

### ISSUE THREAD

**Issue by ant811** [hratx39-blue-ocean/deep-dive#25]
As a user, I want to be able to scroll through candidates so that I can see every candidate.

Acceptance Criteria:

Candidate info page:
 - Displays an image of the candidate
 - Gives a brief, neutral overview of the candidates's life.
- Links to twitter and campaign.
 - There is a top navigation bar.

**Comment by ant811** [comment]
Acceptance Criteria:
 - Page renders grid of all candidates
 - User can scroll through list
 - When user clicks on candidate, the user is re-directed to that candidates information page.

**Comment by scottkelder** [comment]
This was broken into two tickets: this ticket is for the candidate info page and #78 is the ticket for the scrollable list.
