### ISSUE TITLE
As a user, I want to be able to click on a navigation button and be redirected to the voting detail specific landing page.

### ISSUE THREAD

**Issue by ant811** [hratx39-blue-ocean/deep-dive#30]
Acceptance Criteria:
 - This is the "Voter Info Details" landing page
 - There is side navigation bar for each of the following:  
   - Polling station Info
   - State Registration Laws
   - Where to, and how to register, to Vote
   - Am I registered to vote
- Each of the four bulleted items above also appear as cards on the page.
 - Clicking on the navigation link, or the card, renders that items details on the page.  The page does not reload, and the navigation bar stays so that the user can navigate amongst all four items

**Comment by seeThisThrough** [comment]
working on this with Anthony
