### ISSUE TITLE
Create Header (footer if time)

### ISSUE THREAD

**Issue by ssspear** [hratx39-blue-ocean/deep-dive#62]
Why: Our voter will have a consistent experience with every page having a header & footer. 

How: Our voter knows that they are using our application because there is a header and footer on every page. They also have a clear understanding of hierarchy on the page.

Acceptance criteria:
- Each component has a similar style consistent with the rest of the application
- Header component gives our voter an understanding that they are using our application
- Footer component contains relevant application information (TBD)

**Comment by Dan-Kaiser** [comment]
Just header, footer can be extra
