### ISSUE TITLE
As a voter, I want to know what I am required to bring with me to the voting station so I don’t have issues voting when I arrive.

### ISSUE THREAD

**Issue by ant811** [hratx39-blue-ocean/deep-dive#8]

**Comment by ant811** [comment]
Acceptance Criteria:
 - Displays required documentation
 - Displays documentation that does NOT fit the criteria of what is required
 - This will go into the "Polling station info" card

**Comment by lrouan** [comment]
Escalated from 2 to a 3 due to webscraping (could not find an api)
